# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: disable

plugins:
  - rubocop-rspec

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# Force frozen_string_literal comment at the top of files
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Force the use of 'when' in RSpec contexts
RSpec/ContextWording:
  Enabled: true
  Prefixes:
    - when
    - with
    - without

# New cops added to RuboCop RSpec
RSpec/IncludeExamples:
  Enabled: true

# Allow deeper nesting in RSpec example groups
RSpec/NestedGroups:
  Max: 4

# Allow multiple expectations per example
RSpec/MultipleExpectations:
  Max: 2

# Allow multiple memoized helpers (let/let!) in RSpec example groups
RSpec/MultipleMemoizedHelpers:
  Max: 8
