version: '3'

services:
  db:
    image: docker.io/postgres:16
    environment:
      POSTGRES_DB: api_frame_circles_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: test
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        bundle install &&
        ./bin/rails db:create db:migrate RAILS_ENV=test &&
        bundle exec rspec &&
        echo 'Tests completed successfully!' &&
        exit 0
      "

volumes:
  postgres_test_data:
  bundle_cache:
