version: '3'

services:
  db:
    image: docker.io/postgres:16
    environment:
      POSTGRES_DB: api_frame_circles_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        bundle install &&
        ./bin/rails db:create db:migrate db:seed &&
        ./bin/rails server -b 0.0.0.0 -p 3000
      "

volumes:
  postgres_data:
  bundle_cache:
